### ISSUE TITLE
Support for nRF51

### ISSUE THREAD

**Issue by EdgarDiez** [NordicPlayground/nrf5-sdk-for-eddystone#3]
Good job with the implementation for nRF52, it works great! 
When support for nRF51?

Thanks!

**Comment by tonywu-nordicsemi** [comment]
Glad to know that it's working great for you :). There are also some improvements coming quite soon as well!

As for nRF51 support I'm sorry to say that we don't have a fixed date for it yet as there are many other pieces we have to pull together first. But it's in the pipeline!

**Comment by YoussF** [comment]
Hi all,

Is there any new about this ? i just bought a nrf51-dk (i costed me 79,60 € which is a lot for a student) and i can't wait to play with the eddystone frame format.

Thank a lot.
Youssef.

**Comment by hakonfam** [comment]
You can find a experimental version of Eddystone with nRF51 support in nRF5 SDK version 12.2.0.

A future 12.x release will have nRF51 support in production quality. No schedule is set for this.

nRF5 SDK version 13.0.0 has production quality nRF52 version of Eddystone.

If I were you, I would take the code from SDK 13.0.0 and patch it to the nRF51 Eddystone project in SDK 12.2.0.
